services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: manila
      POSTGRES_PASSWORD: manila
      POSTGRES_DB: manila
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache-server:
    build:
      context: ./services/cache-server
      dockerfile: Dockerfile
    environment:
      PORT: 2995
      AUTH_TOKEN: manila
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: manila
      DB_PASSWORD: manila
      DB_NAME: manila
    ports:
      - "2995:2995"
    depends_on:
      - db

volumes:
  db_data:
